name: Aks Deploy Karna hoga
on: workflow_dispatch

permissions:
  contents: read
  id-token: write
jobs:
  azlogin: 
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: az-login
      uses: azure/login@v2.3.0
    
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Terraform
  # You may pin to the exact commit or the version.
  # uses: little-core-labs/install-terraform@1e577535d279f1999a5abf60337ddc3ff225e79d
  uses: little-core-labs/install-terraform@v2.0.0
  with:
    # Version of terraform to download
    version: 1.13.1
      
    - name: Terraform init
      run: terraform init
      working-directory: Aks-Acr/Aks_cluster

    - name: Terraform Plan
      run: terraform plan
      working-directory: Aks-Acr/Aks_cluster


