name: infra_deploy
on: workflow_dispatch
jobs:
  terraform: 
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  terraform-Init:
    runs-on: ubuntu-latest
    environment: test
    needs: terraform   # ye job login ke baad chalega
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: terraformInit
        run: terraform init
      - name: terraformApply 
        run: terraform apply --auto-approve
  
